. (Join-Path $PSScriptRoot "Common.ps1")
. (Join-Path $PSScriptRoot "PlatformRegistry.ps1")

function Invoke-AhoAgentsMaterialize {
    param(
        [Parameter(Mandatory)][string]$Target,
        [string]$TemplateRoot = (Get-AhoYourProject)
    )
    $srcAgents = Join-Path $TemplateRoot ".agents\agents"
    $dstAgents = Join-Path $Target ".agents\agents"
    $copied = @()
    $generated = @()
    if (Test-Path -LiteralPath $srcAgents) {
        New-Item -ItemType Directory -Path $dstAgents -Force | Out-Null
        Get-ChildItem -LiteralPath $srcAgents -Filter "*.md" -File | ForEach-Object {
            $dest = Join-Path $dstAgents $_.Name
            if (-not (Test-Path -LiteralPath $dest)) {
                Copy-Item -LiteralPath $_.FullName -Destination $dest
                $copied += $_.Name
            }
            $base = [IO.Path]::GetFileNameWithoutExtension($_.Name)
            $raw = Get-Content -LiteralPath $_.FullName -Raw -Encoding UTF8
            $desc = $base
            if ($raw -match '(?m)^description:\s*(.+)$') { $desc = $Matches[1].Trim() }
            $name = $base
            if ($raw -match '(?m)^name:\s*(.+)$') { $name = $Matches[1].Trim() }

            $agentPlatforms = Get-AhoPlatformsForInstall -Target $Target
            foreach ($plat in $agentPlatforms) {
                $agentsFormat = $plat['project_agents_format']
                $agentsDir = $plat['project_agents_dir']
                if (-not $agentsFormat -or -not $agentsDir) { continue }
                $platName = $plat['name']

                $platAgentsDir = Join-Path $Target $agentsDir
                New-Item -ItemType Directory -Path $platAgentsDir -Force | Out-Null

                if ($agentsFormat -eq 'toml') {
                    $toml = Join-Path $platAgentsDir "$base.toml"
                    if (-not (Test-Path -LiteralPath $toml)) {
                        $escName = $name -replace '\\', '\\\\' -replace '"', '\\"'
                        $escDesc = $desc -replace '\\', '\\\\' -replace '"', '\\"'
                        $devInstructions = ""
                        if ($raw -match '(?s)^---\r?\n.*?---\r?\n(.+)') {
                            $body = $Matches[1].Trim()
                            $devInstructions = $body -replace '\\', '\\\\' -replace '"', '\\"' -replace "`r`n", "`n" -replace "`n", "`n"
                        }
                        $lines = @(
                            "# Generated by aho-setup from .agents/agents/$($_.Name)"
                            "name = `"$escName`""
                            "description = `"$escDesc`""
                        )
                        if (-not [string]::IsNullOrWhiteSpace($devInstructions)) {
                            $lines += "developer_instructions = `"""$devInstructions`""""
                        }
                        $content = $lines -join "`n"
                        $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
                        [System.IO.File]::WriteAllText($toml, $content, $utf8NoBom)
                        $generated += "${platName}:$base.toml"
                    }
                } elseif ($agentsFormat -eq 'markdown') {
                    $mdAgent = Join-Path $platAgentsDir "$base.md"
                    if (-not (Test-Path -LiteralPath $mdAgent)) {
                        $body = ""
                        if ($raw -match '(?s)^---\r?\n.*?---\r?\n(.+)') {
                            $body = $Matches[1].Trim()
                        }
                        $lines = @(
                            "---"
                            "description: $desc"
                            "mode: subagent"
                            "---"
                            $body
                        )
                        $content = $lines -join "`n"
                        $utf8NoBom = [System.Text.UTF8Encoding]::new($false)
                        [System.IO.File]::WriteAllText($mdAgent, $content, $utf8NoBom)
                        $generated += "${platName}:$base.md"
                    }
                }
            }
        }
    }
    return [pscustomobject]@{ copied = $copied; generated = $generated }
}
